// Demo data — clearly fictional for development

export const DEMO_CATEGORIES = [
  { id: '1', slug: 'antiques',   nameAr: 'تحف وأنتيك',    nameEn: 'Antiques',          imageUrl: '/images/cat-antiques.jpg' },
  { id: '2', slug: 'furniture',  nameAr: 'أثاث كلاسيك',   nameEn: 'Classic Furniture', imageUrl: '/images/cat-furniture.jpg' },
  { id: '3', slug: 'art',        nameAr: 'لوحات فنية',    nameEn: 'Art Pieces',        imageUrl: '/images/cat-art.jpg' },
  { id: '4', slug: 'household',  nameAr: 'أواني منزلية',  nameEn: 'Household',         imageUrl: '/images/cat-household.jpg' },
  { id: '5', slug: 'lighting',   nameAr: 'نجف وإضاءة',    nameEn: 'Lighting',          imageUrl: '/images/cat-lighting.jpg' },
  { id: '6', slug: 'rare',       nameAr: 'قطع أثرية',     nameEn: 'Rare Pieces',       imageUrl: '/images/cat-rare.jpg' },
]

export const DEMO_PRODUCTS = [
  {
    id: 'p1', categorySlug: 'household',
    nameAr: 'مزهرية صينية قديمة',        nameEn: 'Antique Chinese Vase',
    slug: 'antique-chinese-vase',
    price: 1850, comparePrice: 2400,
    imageUrl: 'https://images.unsplash.com/photo-1605433247501-698405495b9d?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: false,
    era: '1850م', origin: 'الصين', condition: 'ممتاز',
  },
  {
    id: 'p2', categorySlug: 'antiques',
    nameAr: 'ساعة كلاسيكية فرنسية',      nameEn: 'Classic French Clock',
    slug: 'classic-french-clock',
    price: 2950, comparePrice: undefined,
    imageUrl: 'https://images.unsplash.com/photo-1508169351866-777fc0047ac5?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: true,
    era: '1920م', origin: 'فرنسا', condition: 'جيد جداً',
  },
  {
    id: 'p3', categorySlug: 'furniture',
    nameAr: 'كرسي كلاسيك فاخر',          nameEn: 'Luxury Classic Chair',
    slug: 'luxury-classic-chair',
    price: 3750, comparePrice: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    stock: 2, isUnique: false, isAuctionReady: false,
    era: '1900م', origin: 'إيطاليا', condition: 'ممتاز',
  },
  {
    id: 'p4', categorySlug: 'lighting',
    nameAr: 'نجفة كريستال ذهبية',        nameEn: 'Gold Crystal Chandelier',
    slug: 'gold-crystal-chandelier',
    price: 4200, comparePrice: 5800,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: false,
    era: '1930م', origin: 'النمسا', condition: 'ممتاز',
  },
  {
    id: 'p5', categorySlug: 'antiques',
    nameAr: 'جرامافون أنتيك قديم',       nameEn: 'Vintage Gramophone',
    slug: 'vintage-gramophone',
    price: 2150, comparePrice: undefined,
    imageUrl: 'https://images.unsplash.com/photo-1516737490857-848138c6e0a2?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: true,
    era: '1910م', origin: 'بريطانيا', condition: 'جيد',
  },
  {
    id: 'p6', categorySlug: 'art',
    nameAr: 'لوحة أوروبية أصيلة',        nameEn: 'Original European Painting',
    slug: 'original-european-painting',
    price: 6800, comparePrice: 9000,
    imageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: true,
    era: '1880م', origin: 'فرنسا', condition: 'ممتاز',
  },
  {
    id: 'p7', categorySlug: 'household',
    nameAr: 'طقم شاي بورسيلاني فرنسي',  nameEn: 'French Porcelain Tea Set',
    slug: 'french-porcelain-tea-set',
    price: 2890, comparePrice: 3400,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
    stock: 3, isUnique: false, isAuctionReady: false,
    era: '1900م', origin: 'فرنسا', condition: 'جيد جداً',
  },
  {
    id: 'p8', categorySlug: 'furniture',
    nameAr: 'كرسي جلسة خشب جوز',        nameEn: 'Walnut Wood Armchair',
    slug: 'walnut-wood-armchair',
    price: 2450, comparePrice: undefined,
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: false,
    era: '1905م', origin: 'إنجلترا', condition: 'جيد',
  },
  {
    id: 'p9', categorySlug: 'rare',
    nameAr: 'مزهرية تاجسهو مرجانية',    nameEn: 'Coral Majolica Vase',
    slug: 'coral-majolica-vase',
    price: 3150, comparePrice: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: true,
    era: '1870م', origin: 'إيطاليا', condition: 'جيد جداً',
  },
  {
    id: 'p10', categorySlug: 'antiques',
    nameAr: 'صندوق مجوهرات قديم',       nameEn: 'Antique Jewelry Box',
    slug: 'antique-jewelry-box',
    price: 1890, comparePrice: undefined,
    imageUrl: 'https://images.unsplash.com/photo-1584811644165-33db81f96b85?w=600&q=80',
    stock: 2, isUnique: false, isAuctionReady: false,
    era: '1920م', origin: 'ألمانيا', condition: 'ممتاز',
  },
  {
    id: 'p11', categorySlug: 'antiques',
    nameAr: 'ساعة حائط أنتيك إنجليزية', nameEn: 'English Antique Wall Clock',
    slug: 'english-antique-wall-clock',
    price: 4990, comparePrice: 6200,
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: true,
    era: '1890م', origin: 'إنجلترا', condition: 'ممتاز',
  },
  {
    id: 'p12', categorySlug: 'household',
    nameAr: 'طقم أواني فضية سويسرية',   nameEn: 'Swiss Silver Tableware Set',
    slug: 'swiss-silver-tableware',
    price: 5200, comparePrice: undefined,
    imageUrl: 'https://images.unsplash.com/photo-1578374173705-969cbe6f2d6b?w=600&q=80',
    stock: 1, isUnique: true, isAuctionReady: false,
    era: '1895م', origin: 'سويسرا', condition: 'ممتاز',
  },
]

export const DEMO_AUCTIONS = [
  {
    id: 'a1', productId: 'p2',
    nameAr: 'ساعة كلاسيكية فرنسية',      nameEn: 'Classic French Clock',
    imageUrl: 'https://images.unsplash.com/photo-1508169351866-777fc0047ac5?w=600&q=80',
    startingPrice: 2000, currentBid: 2950, bidCount: 12,
    endsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 14 * 60 * 60 * 1000 + 18 * 60 * 1000),
    status: 'ACTIVE' as const,
  },
  {
    id: 'a2', productId: 'p6',
    nameAr: 'لوحة أوروبية أصيلة',        nameEn: 'Original European Painting',
    imageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=600&q=80',
    startingPrice: 5000, currentBid: 6800, bidCount: 8,
    endsAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 9 * 60 * 60 * 1000 + 47 * 60 * 1000),
    status: 'ACTIVE' as const,
  },
  {
    id: 'a3', productId: 'p9',
    nameAr: 'مزهرية تاجسهو مرجانية',    nameEn: 'Coral Majolica Vase',
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    startingPrice: 2500, currentBid: 3150, bidCount: 15,
    endsAt: new Date(Date.now() + 0 * 24 * 60 * 60 * 1000 + 0 * 60 * 60 * 1000 + 18 * 60 * 1000 + 44 * 1000),
    status: 'ACTIVE' as const,
  },
  {
    id: 'a4', productId: 'p11',
    nameAr: 'نجفة كريستال فرنسية كلاسيكية', nameEn: 'French Crystal Chandelier',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    startingPrice: 3500, currentBid: 4200, bidCount: 21,
    endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 22 * 60 * 60 * 1000 + 15 * 60 * 1000),
    status: 'ACTIVE' as const,
  },
]

export const DEMO_TESTIMONIALS = [
  {
    id: '1',
    nameAr: 'فيصل العتيبي',  nameEn: 'Faisal Al-Otaibi',
    cityAr: 'الدمام', cityEn: 'Dammam',
    rating: 5,
    commentAr: 'تعامل رائع وسريع في الشحن، القطعة التي اشتريتها تجاوزت توقعاتي وقد أهديتها كهدية فكانت محل إعجاب الجميع.',
    commentEn: 'Outstanding service and fast shipping. The piece I bought exceeded my expectations and was a wonderful gift.',
    avatar: 'ف',
  },
  {
    id: '2',
    nameAr: 'سارة المطيري',  nameEn: 'Sara Al-Mutairi',
    cityAr: 'جدة', cityEn: 'Jeddah',
    rating: 5,
    commentAr: 'قطع فاخرة ذات جودة عالية والتقييم دقيق جداً. أنصح كل عشاق الأنتيك بالتسوق من هنا.',
    commentEn: 'High-quality luxury pieces with accurate valuation. I recommend every antique lover to shop here.',
    avatar: 'س',
  },
  {
    id: '3',
    nameAr: 'عبدالله الحربي', nameEn: 'Abdullah Al-Harbi',
    cityAr: 'الرياض', cityEn: 'Riyadh',
    rating: 5,
    commentAr: 'خدمة رائعة ومنتجات أصيلة 100٪. تجربة تسوق ممتعة جداً في كل مرة.',
    commentEn: '100% authentic products and excellent service. A very enjoyable shopping experience every time.',
    avatar: 'ع',
  },
]
